repos:
  - hooks:
      - id: autoflake
        exclude: |
          (?x)^(
              ./migrations/.|
              configuracion/|
              ./apps.py|
              manage.py|
              ./__init__.py|
          )$

    repo: https://github.com/PyCQA/autoflake
    rev: v2.0.1

  - hooks:
      - id: isort
        exclude: |
          (?x)^(
              ./migrations/.|
              configuracion/|
              ./apps.py|
              manage.py|
          )$
    repo: https://github.com/pycqa/isort
    rev: 5.12.0

  - hooks:
      - id: black
        language_version: python3.11
        exclude: |
          (?x)^(
              ./migrations/.|
              configuracion/|
              ./apps.py|
              manage.py|
          )$
        stages:
          - commit
    repo: https://github.com/psf/black
    rev: 23.1.0

  - hooks:
      - id: pylint
        name: pylint
        language: system
        types: [ python ]
        pass_filenames: false
        entry: bash -c 'pylint api apps'
    repo: local

  - hooks:
      - id: commitizen
        stages:
          - commit-msg
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0


