version: '3'

services:

  dyp:
    build: .
    command: gunicorn --bind :8000 --workers 4 --threads 4 --timeout 30 configuracion.wsgi:application
    ports:
      - "8000:8000"
    env_file:
      - .env
