# Generated by Django 3.1.3 on 2024-04-18 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Product Name"
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("stock", models.IntegerField(verbose_name="Stock Quantity")),
                ("expiry_date", models.DateTimeField(verbose_name="Expiry Date")),
            ],
            options={
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.CreateModel(
            name="Alarm",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert_type",
                    models.CharField(max_length=20, verbose_name="Alert Type"),
                ),
                ("alert_date", models.DateField(verbose_name="Alert Date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is Active"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="webApp.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alarm",
                "verbose_name_plural": "Alarms",
            },
        ),
    ]
