# Generated by Django 3.1.3 on 2024-04-21 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarms",
                to="webApp.product",
                verbose_name="Product",
            ),
        ),
    ]
