# Generated by Django 3.1.3 on 2024-04-21 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0002_auto_20240420_2157"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alarms",
                to="webApp.product",
            ),
        ),
    ]
