# Generated by Django 3.1.3 on 2024-04-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0003_auto_20240420_2304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="expiry_date",
            field=models.DateField(verbose_name="Expiry Date"),
        ),
    ]
