# Generated by Django 5.0.4 on 2024-04-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0004_auto_20240422_1538"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
