# Generated by Django 3.1.3 on 2024-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webApp", "0005_alter_alarm_id_alter_product_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alarm",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
