# Generated by Django 3.1.3 on 2024-07-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backoffice", "0002_alter_administrator_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="administrator",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
